// Mocks generated by Mockito 5.4.6 from annotations
// in nexshift_app/test/unit/features/replacement/services/crew_allocator_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nexshift_app/core/data/models/vehicle_rule_set_model.dart'
    as _i4;
import 'package:nexshift_app/core/repositories/vehicle_rules_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [VehicleRulesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVehicleRulesRepository extends _i1.Mock
    implements _i2.VehicleRulesRepository {
  MockVehicleRulesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.VehicleRuleSet?> getRules({
    required String? vehicleType,
    String? stationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRules, [], {
              #vehicleType: vehicleType,
              #stationId: stationId,
            }),
            returnValue: _i3.Future<_i4.VehicleRuleSet?>.value(),
          )
          as _i3.Future<_i4.VehicleRuleSet?>);

  @override
  _i3.Future<void> saveStationRules(_i4.VehicleRuleSet? ruleSet) =>
      (super.noSuchMethod(
            Invocation.method(#saveStationRules, [ruleSet]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteStationRules({
    required String? vehicleType,
    required String? stationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStationRules, [], {
              #vehicleType: vehicleType,
              #stationId: stationId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.VehicleRuleSet>> getAllStationRules(String? stationId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllStationRules, [stationId]),
            returnValue: _i3.Future<List<_i4.VehicleRuleSet>>.value(
              <_i4.VehicleRuleSet>[],
            ),
          )
          as _i3.Future<List<_i4.VehicleRuleSet>>);

  @override
  _i3.Future<bool> hasCustomRules({
    required String? vehicleType,
    required String? stationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#hasCustomRules, [], {
              #vehicleType: vehicleType,
              #stationId: stationId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.VehicleRuleSet?> createDefaultRulesForStation({
    required String? vehicleType,
    required String? stationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDefaultRulesForStation, [], {
              #vehicleType: vehicleType,
              #stationId: stationId,
            }),
            returnValue: _i3.Future<_i4.VehicleRuleSet?>.value(),
          )
          as _i3.Future<_i4.VehicleRuleSet?>);
}
